#!/bin/bash -e

# Example input file:
#
# SodaCost                2    # Manufacturer Suggested Retail Price (MSRP) per bottle
# NumStudents             2    # number of students to create
# MaxPurchases            8    # maximum number of bottles a student purchases
# NumVendingMachines      3    # number of vending machines
# MaxStockPerFlavour      5    # maximum number of bottles of each flavour in a vending machine
# MaxShippedPerFlavour    3    # maximum number of bottles of each flavour generated by the bottling
#                              #    plant per production run
# TimeBetweenShipments    3    # length of time between shipment pickup
# ParentalDelay           2    # length of time between new deposits of funds
# NumCouriers             1    # maximum number of couriers in the pool

`touch testfile.config`

for SodaCost in `seq 1 6`;
do
for NumStudents in `seq 1 5`;
do
for MaxPurchases in `seq 1 3`;
do
for NumVendingMachines in `seq 1 3`;
do
for MaxStockPerFlavour in `seq 1 2`;
do
for MaxShippedPerFlavour in `seq 1 2`;
do
for TimeBetweenShipments in `seq 4 4`;
do
for ParentalDelay in `seq 1 1`;
do
for NumCouriers in `seq 1 2`;
do
for seed in `seq 1 3`;
do

`echo "SodaCost $SodaCost
NumStudents $NumStudents
MaxPurchases $MaxPurchases
NumVendingMachines $NumVendingMachines
MaxStockPerFlavour $MaxStockPerFlavour
MaxShippedPerFlavour $MaxShippedPerFlavour
TimeBetweenShipments $TimeBetweenShipments
ParentalDelay $ParentalDelay
NumCouriers $NumCouriers
" >  testfile.config`

echo "Running soda testfile.config $seed"
`./soda testfile.config $seed >/dev/null`

done
done
done
done
done
done
done
done
done
done

echo "VERIFICATION FINISHED."
